My app
dafnemus/cursoMobileFirst pull request #3
Opened 2021-06-29 20:49 UTC by dafnemus

Realice, lo más parecido posible el clone de este [figma](https://www.figma.com/file/sMmlQaZldfDcLERYYWe6h4/Bata-Bit?node-id=44%3A594) 
Solo realice la parte mobile.
![Captura de pantalla de 2021-06-29 17-47-07](https://user-images.githubusercontent.com/57498199/123865430-4bcfbe80-d902-11eb-99b2-7f5de9423d36.png)

2021-06-29 21:41 UTC, briangerez requested changes
Gran trabajo, Daf! 🎉 

Te dejo unos comentarios sutiles que te van a ayudar a mantener una misma estructura de código para el proyecto!

Un detalle, para los PRs, podrías subir una imagen gif de cómo se ve la aplicación. Si es que hay interacción. Además de una imagen del diseño que estás replicando para poder compararlo!

Seguí así, dalee

2021-06-29 21:41 UTC, briangerez commented on Batatabit/main.css
> +  font-family: 'Inter', sans-serif;
Si este font es utilizado en toda la app, podrías setearlo en los estilos del body y no pasarlo en cada estilo donde se use. 

Si no es global a toda la app, veo que se usa en el main, capaz sería agregarlo ahí una vez y no repetirlo en otros lugares

2021-06-29 21:41 UTC, briangerez commented on Batatabit/main.css
> +  position: absolute;
Creo que deberías agregar el top: 0; ya que para el position absolute es necesario

2021-06-29 21:41 UTC, briangerez commented on Batatabit/main.css
> +  left: 43%;
Aquí, podrías usar un porcentaje más redondeado y restarle algunos pixeles, como te decía ayer, quizas para otros dispositivos no quede bien este porcentaje. 

Sin embargo, si vez que este porcentaje está ok, lo dejamos por ahoraa

2021-06-29 21:41 UTC, briangerez commented on Batatabit/main.css
> +  box-shadow: 2px 2px 2px 2px #b2b0abd1;
Creo que con poner asi estaría bien igual,

```suggestion
  box-shadow: 2px  #b2b0abd1;
```

2021-06-29 21:41 UTC, briangerez commented on Batatabit/main.css
> +  color: black;
Nosotros en los proyectos tenemos definidos los colores como constantes. Aquí no es necesario agregarlos, pero si podemos definir cómo queremos escribir los colores. Aquí lo estás haciendo con el nombre "black" pero para tener consistencia podrías agregarlo en formato hexadecimal: #000000 y así con el resto de los colores

```suggestion
  color: #000000;
```

2021-06-29 21:41 UTC, briangerez commented on Batatabit/main.css
> +  align-items: center;
Este estilo te lo está tomando? Porque no está seteado un display-flex para este footer

2021-06-29 21:41 UTC, briangerez commented on Batatabit/main.css
> +  color:  #3c4043;
```suggestion
  color: #3c4043;
```

2021-06-29 21:41 UTC, briangerez commented on Batatabit/main.css
> +  justify-content:flex-start;
```suggestion
  justify-content: flex-start;
```

2021-06-29 21:41 UTC, briangerez commented on Batatabit/main.css
> +main .table-contain #title-table {
Me parece un muy buen concepto usar IDs para dar estilos. Aunque, en la mayoría de los proyectos donde trabajé, no los usé. 
Creo que con agregarle una clase en vez de un ID funciona de igual manera, y mantenemos una estructura similar a todo el código (además de por un tema de especificidad)

2021-06-30 13:07 UTC, dafnemus commented on Batatabit/main.css
> +  font-family: 'Inter', sans-serif;
Este font solo se aplica a dos componentes, por eso lo paso directamente. Porque la fuente principal es DM sans que esta en el body. Pero revisando en este caso lo pase a la clase `table-contain` para que quede genérico y no repetirlo dos veces dentro del msmo componente.i

2021-06-30 13:09 UTC, dafnemus commented on Batatabit/main.css
> +  position: absolute;
Eh no, pq si le agrego top 0 me lleva el componente arriba del header, y necesito que quede en medio de la sección 1 y la sección 2 del main

2021-06-30 13:12 UTC, dafnemus commented on Batatabit/main.css
> +  left: 43%;
Genial lo pase a pixeles en vez de 43%, puse 155px

2021-06-30 13:16 UTC, dafnemus commented on Batatabit/main.css
> +  box-shadow: 2px 2px 2px 2px #b2b0abd1;
`box-shadow: 2px 2px #b2b0abd1` es, porque el que me recomendaste me lo marca como error el inspector de google

2021-06-30 13:18 UTC, dafnemus commented on Batatabit/main.css
> +  color: black;
Tomo la sugerencia del formato hexadecimal. En la próxima actividad aplicaré lo de las constantes

2021-06-30 13:22 UTC, dafnemus commented on Batatabit/main.css
> +  align-items: center;
De hecho si me lo toma, porque estoy usando display: grid. Y este usa align para alinear elementos.

[https://developer.mozilla.org/es/docs/Web/CSS/CSS_Grid_Layout/Box_Alignment_in_CSS_Grid_Layout](url)

2021-06-30 13:28 UTC, dafnemus commented on Batatabit/main.css
> +main .table-contain #title-table {
Genial, pase los ID a clases.

2021-07-20 17:48 UTC, merged