Version final
dafnemus/cursoMobileFirst pull request #4
Opened 2021-07-01 16:27 UTC by dafnemus

# **Esta es la versión final de Batatabit. No seguí el 100% de este [figma.](https://www.figma.com/file/sMmlQaZldfDcLERYYWe6h4/Bata-Bit?node-id=44%3A593)**

## **Iteración de la página en mobile.**
  ![batata](https://user-images.githubusercontent.com/57498199/124156243-c1a46900-da6d-11eb-95d3-4a6fb045d71e.gif)

## **En el gift para mobile  y para tablets las card plans aparecen en forma de scroll horizontal, mientras que para laptops no.**
![Captura de pantalla de 2021-07-01 13-08-28](https://user-images.githubusercontent.com/57498199/124156790-6e7ee600-da6e-11eb-94cc-328623794f65.png)

## **Resolucion de pantalla a partir de 760px para tablets:**
![Captura de pantalla de 2021-07-01 13-09-02](https://user-images.githubusercontent.com/57498199/124156346-e993cc80-da6d-11eb-90c1-a4dd5a9fd730.png)

## **Resolución de pantalla a partir de 1200px para laptops:**
![Captura de pantalla de 2021-07-01 13-08-40](https://user-images.githubusercontent.com/57498199/124156467-0d571280-da6e-11eb-8962-f7bfd0c8e9af.png)

## **Esta sección también se modifica a partir de 1200:**
![Captura de pantalla de 2021-07-01 13-17-21](https://user-images.githubusercontent.com/57498199/124157110-c9b0d880-da6e-11eb-840c-575e0993b910.png)

2021-07-02 14:36 UTC, briangerez requested changes
Excelente trabajo!! 💯 

Dejo algunos comentarios que pueden sumar a la legibilidad del código y un detalle con la palabra `información`. Me gustó mucho como quedó el maquetado! Funciona bien en el responsive del navegador! Seguí así 🚀

2021-07-02 14:36 UTC, briangerez commented on Batatabit/index.html
> +                    <p>Nuestro API toma informavión minuto a minuto sobre las tasas que más determinan el comportamiento.</p>
```suggestion
                    <p>Nuestro API toma información minuto a minuto sobre las tasas que más determinan el comportamiento.</p>
```

2021-07-02 14:36 UTC, briangerez commented on Batatabit/main.css
> +  top: calc(0% - 18.5px);
Genial!!

2021-07-02 14:36 UTC, briangerez commented on Batatabit/main.css
> +main .contain-cards::-webkit-scrollbar {
```suggestion
}

main .contain-cards::-webkit-scrollbar {
```

Te marco eso como un detalle para contarte que en los proyectos tratamos de mantener una misma identación (por lo general 2 espacios) y cada clase o estilo separado por una línea. Está muy prolijo este archivo! Lo marco para que lo tengas en cuenta no más 😄

2021-07-02 14:36 UTC, briangerez commented on Batatabit/main.css
> +  margin: 21px 0px 20px 9px;
```suggestion
  margin: 21px 0 20px 9px;
```

Otro detalle que no es grave, pero para que sepas que se puede simplificar la sintaxis cuando se quiere indicar 0 píxeles

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/assets/icons/batata.svg
> +<svg width="41" height="25" viewBox="0 0 41 25" fill="none" xmlns="http://www.w3.org/2000/svg">
En general, muy bueno el manejo de las imagenes :).
Por otro lado, te haré la misma recomendación que a Tommy ;). En un proyecto, generalmente uno suele separar los assets que va a usar. Un buen criterio es hacer una separación por logos y todo lo relacionado a branding, y separarlo de icons y de otras imagenes.

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/assets/icons/orange-right-arrow.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Un pequeño truco de los svg es que podemos hacer variaciones en sus colores. Es por esto que recomendaría no usar el color como parte del naming en un asset. En su lugar, para lograr esa diferencia que buscabas entre assets, podrías renombrar a right-arrow como tiny-right-arrow y dejar a esta simplemente como right-arrow ;)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #ffe9d4;
Una pequeña recomendación. Podrías definir los colores más arriba y emplear variables que referencien a una paleta de colores ;)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #fff;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #FFE9D5;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #ffe9d4;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #000;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #757575;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #636261;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #fdfaf7;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #ffe9d4;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #000;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #000000;
Aquí puedes usar el short #000 (te permite usar menos dígitos si los valores se repiten). Por otro lado, recomiendo paleta de colores ;)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #636261;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #555353d7;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #201e1c;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #fff;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #282623;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #9c9999;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #282623;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #fff;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #757575;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #ffe9d4;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #f7931a;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #F7931A;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #ffe9d4;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #fff;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #000000;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #000000;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #757575;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  background-color: #f7931a;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #fff;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #3c4043;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  color: #fff;
Same :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/index.html
> +<!DOCTYPE html>
Buen manejo de tags :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  font-size: 15px;
Una recomendación Daf con respecto a los font-size. Al emplear px, en lugar de rem o em (recomiendo la primera ;) ), no tenes la posibilidad de realizar cambios a nivel proyecto facilmente.
Si por ejemplo te dijeran "quiero que los textos se vean un poco más grandes", empleando rem el cambio se hace muy sencillo ;)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  position: relative;
Necesitamos esta prop?

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  left: calc(50% - 130px);
Nice :)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  margin: 0;
Podes evitar tener que lidiar con esto en más de un caso empleando el tag 
* {
  padding: 0,
  margin: 0,
}
Y de ese modo definirlo una sola vez ;)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  height:20px;
```suggestion
  height: 20px;
```

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  position: relative;
Necesitamos esta prop?

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  padding: 0;
;)

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +  position: relative;
Necesitamos esta prop?

2021-07-06 19:25 UTC, Distance71 commented on Batatabit/main.css
> +}
La podemos borrar con el truco que te comenté más arriba ;)

2021-07-08 20:59 UTC, dafnemus commented on Batatabit/index.html
> +                    <p>Nuestro API toma informavión minuto a minuto sobre las tasas que más determinan el comportamiento.</p>
Corregido

2021-07-08 20:59 UTC, dafnemus commented on Batatabit/main.css
> +  top: calc(0% - 18.5px);
👍🏼

2021-07-08 21:00 UTC, dafnemus commented on Batatabit/main.css
> +main .contain-cards::-webkit-scrollbar {
corregí la identación el los archivos css

2021-07-08 21:00 UTC, dafnemus commented on Batatabit/main.css
> +  margin: 21px 0px 20px 9px;
Corregido

2021-07-08 21:01 UTC, dafnemus commented on Batatabit/assets/icons/batata.svg
> +<svg width="41" height="25" viewBox="0 0 41 25" fill="none" xmlns="http://www.w3.org/2000/svg">
Lo tomo para la proxíma

2021-07-08 21:01 UTC, dafnemus commented on Batatabit/assets/icons/orange-right-arrow.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Tomo el comentario, ya le cambie el nombre al icono

2021-07-08 21:34 UTC, dafnemus commented on Batatabit/main.css
> +  position: relative;
Si pq afecta al componente de recomendado, que posee absolute

2021-07-08 21:35 UTC, dafnemus commented on Batatabit/main.css
> +  height:20px;
Corregido

2021-07-08 21:35 UTC, dafnemus commented on Batatabit/main.css
> +  background-color: #ffe9d4;
Listo

2021-07-08 21:40 UTC, dafnemus commented on Batatabit/main.css
> +  position: relative;
Si pq afecta al componente de recomendado, que posee absolute

2021-07-08 21:41 UTC, dafnemus commented on Batatabit/main.css
> +  position: relative;
No, ya la quite

2021-07-20 17:48 UTC, merged